name = input('이름 입력 : ')
email = input('메일 입력 : ')
userId = input('아이디 입력 : ')
password = input('비밀번호 입력 : ')
rrn1 = input('주민번호 앞자리 입력 : ')
rrn2 = input('주민번호 뒷자리 입력 : ')
address = input('주소 입력 : ')

print('-' * 25)
print('이름 :', name)
print('메일 :', email)
print('아이디 :', userId)
print('비밀번호 :', '*' * len(password))
print('주민번호 : {} - {}{}'.format(rrn1, rrn2[0], '*' * (len(rrn2) - 1)))
print('주소 :', address)
print('-' * 25)
